// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {proto} from '../models';

export function Connect(arg1:string,arg2:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetLatestStats():Promise<proto.LatestStats>;

export function GetTrends(arg1:string,arg2:number):Promise<proto.GetTrendsResponse>;

export function WatchChanges(arg1:string,arg2:number):Promise<void>;
