// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2) {
  return window['go']['main']['App']['Connect'](arg1, arg2);
}

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function GetLatestStats() {
  return window['go']['main']['App']['GetLatestStats']();
}

export function GetTrends(arg1, arg2) {
  return window['go']['main']['App']['GetTrends'](arg1, arg2);
}

export function WatchChanges(arg1, arg2) {
  return window['go']['main']['App']['WatchChanges'](arg1, arg2);
}
