// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: proto/analytics.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlogAnalytics_GetTrends_FullMethodName      = "/vblog.BlogAnalytics/GetTrends"
	BlogAnalytics_GetLatestStats_FullMethodName = "/vblog.BlogAnalytics/GetLatestStats"
	BlogAnalytics_WatchChanges_FullMethodName   = "/vblog.BlogAnalytics/WatchChanges"
	BlogAnalytics_Ping_FullMethodName           = "/vblog.BlogAnalytics/Ping"
)

// BlogAnalyticsClient is the client API for BlogAnalytics service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlogAnalyticsClient interface {
	GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*GetTrendsResponse, error)
	GetLatestStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LatestStats, error)
	WatchChanges(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error)
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type blogAnalyticsClient struct {
	cc grpc.ClientConnInterface
}

func NewBlogAnalyticsClient(cc grpc.ClientConnInterface) BlogAnalyticsClient {
	return &blogAnalyticsClient{cc}
}

func (c *blogAnalyticsClient) GetTrends(ctx context.Context, in *GetTrendsRequest, opts ...grpc.CallOption) (*GetTrendsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTrendsResponse)
	err := c.cc.Invoke(ctx, BlogAnalytics_GetTrends_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAnalyticsClient) GetLatestStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*LatestStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatestStats)
	err := c.cc.Invoke(ctx, BlogAnalytics_GetLatestStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blogAnalyticsClient) WatchChanges(ctx context.Context, in *WatchRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChangeEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BlogAnalytics_ServiceDesc.Streams[0], BlogAnalytics_WatchChanges_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchRequest, ChangeEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlogAnalytics_WatchChangesClient = grpc.ServerStreamingClient[ChangeEvent]

func (c *blogAnalyticsClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, BlogAnalytics_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlogAnalyticsServer is the server API for BlogAnalytics service.
// All implementations must embed UnimplementedBlogAnalyticsServer
// for forward compatibility.
type BlogAnalyticsServer interface {
	GetTrends(context.Context, *GetTrendsRequest) (*GetTrendsResponse, error)
	GetLatestStats(context.Context, *Empty) (*LatestStats, error)
	WatchChanges(*WatchRequest, grpc.ServerStreamingServer[ChangeEvent]) error
	Ping(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedBlogAnalyticsServer()
}

// UnimplementedBlogAnalyticsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlogAnalyticsServer struct{}

func (UnimplementedBlogAnalyticsServer) GetTrends(context.Context, *GetTrendsRequest) (*GetTrendsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTrends not implemented")
}
func (UnimplementedBlogAnalyticsServer) GetLatestStats(context.Context, *Empty) (*LatestStats, error) {
	return nil, status.Error(codes.Unimplemented, "method GetLatestStats not implemented")
}
func (UnimplementedBlogAnalyticsServer) WatchChanges(*WatchRequest, grpc.ServerStreamingServer[ChangeEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchChanges not implemented")
}
func (UnimplementedBlogAnalyticsServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedBlogAnalyticsServer) mustEmbedUnimplementedBlogAnalyticsServer() {}
func (UnimplementedBlogAnalyticsServer) testEmbeddedByValue()                       {}

// UnsafeBlogAnalyticsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlogAnalyticsServer will
// result in compilation errors.
type UnsafeBlogAnalyticsServer interface {
	mustEmbedUnimplementedBlogAnalyticsServer()
}

func RegisterBlogAnalyticsServer(s grpc.ServiceRegistrar, srv BlogAnalyticsServer) {
	// If the following call panics, it indicates UnimplementedBlogAnalyticsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlogAnalytics_ServiceDesc, srv)
}

func _BlogAnalytics_GetTrends_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTrendsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAnalyticsServer).GetTrends(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAnalytics_GetTrends_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAnalyticsServer).GetTrends(ctx, req.(*GetTrendsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAnalytics_GetLatestStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAnalyticsServer).GetLatestStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAnalytics_GetLatestStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAnalyticsServer).GetLatestStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlogAnalytics_WatchChanges_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlogAnalyticsServer).WatchChanges(m, &grpc.GenericServerStream[WatchRequest, ChangeEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BlogAnalytics_WatchChangesServer = grpc.ServerStreamingServer[ChangeEvent]

func _BlogAnalytics_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlogAnalyticsServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlogAnalytics_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlogAnalyticsServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// BlogAnalytics_ServiceDesc is the grpc.ServiceDesc for BlogAnalytics service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlogAnalytics_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vblog.BlogAnalytics",
	HandlerType: (*BlogAnalyticsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTrends",
			Handler:    _BlogAnalytics_GetTrends_Handler,
		},
		{
			MethodName: "GetLatestStats",
			Handler:    _BlogAnalytics_GetLatestStats_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _BlogAnalytics_Ping_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchChanges",
			Handler:       _BlogAnalytics_WatchChanges_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/analytics.proto",
}
