// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/analytics.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrendsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Granularity   string                 `protobuf:"bytes,1,opt,name=granularity,proto3" json:"granularity,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendsRequest) Reset() {
	*x = GetTrendsRequest{}
	mi := &file_proto_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendsRequest) ProtoMessage() {}

func (x *GetTrendsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendsRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *GetTrendsRequest) GetGranularity() string {
	if x != nil {
		return x.Granularity
	}
	return ""
}

func (x *GetTrendsRequest) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TrendPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=label,proto3" json:"label,omitempty"`
	Pv            int64                  `protobuf:"varint,2,opt,name=pv,proto3" json:"pv,omitempty"`
	Uv            int64                  `protobuf:"varint,3,opt,name=uv,proto3" json:"uv,omitempty"`
	ViewTotal     int64                  `protobuf:"varint,4,opt,name=view_total,json=viewTotal,proto3" json:"view_total,omitempty"`
	CommentCount  int64                  `protobuf:"varint,5,opt,name=comment_count,json=commentCount,proto3" json:"comment_count,omitempty"`
	PostCount     int64                  `protobuf:"varint,6,opt,name=post_count,json=postCount,proto3" json:"post_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendPoint) Reset() {
	*x = TrendPoint{}
	mi := &file_proto_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendPoint) ProtoMessage() {}

func (x *TrendPoint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendPoint.ProtoReflect.Descriptor instead.
func (*TrendPoint) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TrendPoint) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *TrendPoint) GetPv() int64 {
	if x != nil {
		return x.Pv
	}
	return 0
}

func (x *TrendPoint) GetUv() int64 {
	if x != nil {
		return x.Uv
	}
	return 0
}

func (x *TrendPoint) GetViewTotal() int64 {
	if x != nil {
		return x.ViewTotal
	}
	return 0
}

func (x *TrendPoint) GetCommentCount() int64 {
	if x != nil {
		return x.CommentCount
	}
	return 0
}

func (x *TrendPoint) GetPostCount() int64 {
	if x != nil {
		return x.PostCount
	}
	return 0
}

type GetTrendsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Points        []*TrendPoint          `protobuf:"bytes,1,rep,name=points,proto3" json:"points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendsResponse) Reset() {
	*x = GetTrendsResponse{}
	mi := &file_proto_analytics_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendsResponse) ProtoMessage() {}

func (x *GetTrendsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendsResponse.ProtoReflect.Descriptor instead.
func (*GetTrendsResponse) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{2}
}

func (x *GetTrendsResponse) GetPoints() []*TrendPoint {
	if x != nil {
		return x.Points
	}
	return nil
}

type LatestStats struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PvToday            int64                  `protobuf:"varint,1,opt,name=pv_today,json=pvToday,proto3" json:"pv_today,omitempty"`
	UvToday            int64                  `protobuf:"varint,2,opt,name=uv_today,json=uvToday,proto3" json:"uv_today,omitempty"`
	TotalPosts         int64                  `protobuf:"varint,3,opt,name=total_posts,json=totalPosts,proto3" json:"total_posts,omitempty"`
	TotalViews         int64                  `protobuf:"varint,4,opt,name=total_views,json=totalViews,proto3" json:"total_views,omitempty"`
	TotalComments      int64                  `protobuf:"varint,5,opt,name=total_comments,json=totalComments,proto3" json:"total_comments,omitempty"`
	TotalTags          int64                  `protobuf:"varint,6,opt,name=total_tags,json=totalTags,proto3" json:"total_tags,omitempty"`
	PvYesterday        int64                  `protobuf:"varint,7,opt,name=pv_yesterday,json=pvYesterday,proto3" json:"pv_yesterday,omitempty"`
	UvYesterday        int64                  `protobuf:"varint,8,opt,name=uv_yesterday,json=uvYesterday,proto3" json:"uv_yesterday,omitempty"`
	ViewsTodayDelta    int64                  `protobuf:"varint,9,opt,name=views_today_delta,json=viewsTodayDelta,proto3" json:"views_today_delta,omitempty"`
	CommentsTodayDelta int64                  `protobuf:"varint,10,opt,name=comments_today_delta,json=commentsTodayDelta,proto3" json:"comments_today_delta,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LatestStats) Reset() {
	*x = LatestStats{}
	mi := &file_proto_analytics_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatestStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatestStats) ProtoMessage() {}

func (x *LatestStats) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatestStats.ProtoReflect.Descriptor instead.
func (*LatestStats) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{3}
}

func (x *LatestStats) GetPvToday() int64 {
	if x != nil {
		return x.PvToday
	}
	return 0
}

func (x *LatestStats) GetUvToday() int64 {
	if x != nil {
		return x.UvToday
	}
	return 0
}

func (x *LatestStats) GetTotalPosts() int64 {
	if x != nil {
		return x.TotalPosts
	}
	return 0
}

func (x *LatestStats) GetTotalViews() int64 {
	if x != nil {
		return x.TotalViews
	}
	return 0
}

func (x *LatestStats) GetTotalComments() int64 {
	if x != nil {
		return x.TotalComments
	}
	return 0
}

func (x *LatestStats) GetTotalTags() int64 {
	if x != nil {
		return x.TotalTags
	}
	return 0
}

func (x *LatestStats) GetPvYesterday() int64 {
	if x != nil {
		return x.PvYesterday
	}
	return 0
}

func (x *LatestStats) GetUvYesterday() int64 {
	if x != nil {
		return x.UvYesterday
	}
	return 0
}

func (x *LatestStats) GetViewsTodayDelta() int64 {
	if x != nil {
		return x.ViewsTodayDelta
	}
	return 0
}

func (x *LatestStats) GetCommentsTodayDelta() int64 {
	if x != nil {
		return x.CommentsTodayDelta
	}
	return 0
}

type WatchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApiKey        string                 `protobuf:"bytes,1,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	SinceId       int64                  `protobuf:"varint,2,opt,name=since_id,json=sinceId,proto3" json:"since_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_proto_analytics_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{4}
}

func (x *WatchRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *WatchRequest) GetSinceId() int64 {
	if x != nil {
		return x.SinceId
	}
	return 0
}

type ChangeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Detail        string                 `protobuf:"bytes,4,opt,name=detail,proto3" json:"detail,omitempty"`
	Timestamp     string                 `protobuf:"bytes,5,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeEvent) Reset() {
	*x = ChangeEvent{}
	mi := &file_proto_analytics_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeEvent) ProtoMessage() {}

func (x *ChangeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeEvent.ProtoReflect.Descriptor instead.
func (*ChangeEvent) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{5}
}

func (x *ChangeEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ChangeEvent) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ChangeEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *ChangeEvent) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *ChangeEvent) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_analytics_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_analytics_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_analytics_proto_rawDescGZIP(), []int{6}
}

var File_proto_analytics_proto protoreflect.FileDescriptor

const file_proto_analytics_proto_rawDesc = "" +
	"\n" +
	"\x15proto/analytics.proto\x12\x05vblog\"J\n" +
	"\x10GetTrendsRequest\x12 \n" +
	"\vgranularity\x18\x01 \x01(\tR\vgranularity\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"\xa5\x01\n" +
	"\n" +
	"TrendPoint\x12\x14\n" +
	"\x05label\x18\x01 \x01(\tR\x05label\x12\x0e\n" +
	"\x02pv\x18\x02 \x01(\x03R\x02pv\x12\x0e\n" +
	"\x02uv\x18\x03 \x01(\x03R\x02uv\x12\x1d\n" +
	"\n" +
	"view_total\x18\x04 \x01(\x03R\tviewTotal\x12#\n" +
	"\rcomment_count\x18\x05 \x01(\x03R\fcommentCount\x12\x1d\n" +
	"\n" +
	"post_count\x18\x06 \x01(\x03R\tpostCount\">\n" +
	"\x11GetTrendsResponse\x12)\n" +
	"\x06points\x18\x01 \x03(\v2\x11.vblog.TrendPointR\x06points\"\xef\x02\n" +
	"\vLatestStats\x12\x19\n" +
	"\bpv_today\x18\x01 \x01(\x03R\apvToday\x12\x19\n" +
	"\buv_today\x18\x02 \x01(\x03R\auvToday\x12\x1f\n" +
	"\vtotal_posts\x18\x03 \x01(\x03R\n" +
	"totalPosts\x12\x1f\n" +
	"\vtotal_views\x18\x04 \x01(\x03R\n" +
	"totalViews\x12%\n" +
	"\x0etotal_comments\x18\x05 \x01(\x03R\rtotalComments\x12\x1d\n" +
	"\n" +
	"total_tags\x18\x06 \x01(\x03R\ttotalTags\x12!\n" +
	"\fpv_yesterday\x18\a \x01(\x03R\vpvYesterday\x12!\n" +
	"\fuv_yesterday\x18\b \x01(\x03R\vuvYesterday\x12*\n" +
	"\x11views_today_delta\x18\t \x01(\x03R\x0fviewsTodayDelta\x120\n" +
	"\x14comments_today_delta\x18\n" +
	" \x01(\x03R\x12commentsTodayDelta\"B\n" +
	"\fWatchRequest\x12\x17\n" +
	"\aapi_key\x18\x01 \x01(\tR\x06apiKey\x12\x19\n" +
	"\bsince_id\x18\x02 \x01(\x03R\asinceId\"}\n" +
	"\vChangeEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x16\n" +
	"\x06detail\x18\x04 \x01(\tR\x06detail\x12\x1c\n" +
	"\ttimestamp\x18\x05 \x01(\tR\ttimestamp\"\a\n" +
	"\x05Empty2\xe2\x01\n" +
	"\rBlogAnalytics\x12>\n" +
	"\tGetTrends\x12\x17.vblog.GetTrendsRequest\x1a\x18.vblog.GetTrendsResponse\x122\n" +
	"\x0eGetLatestStats\x12\f.vblog.Empty\x1a\x12.vblog.LatestStats\x129\n" +
	"\fWatchChanges\x12\x13.vblog.WatchRequest\x1a\x12.vblog.ChangeEvent0\x01\x12\"\n" +
	"\x04Ping\x12\f.vblog.Empty\x1a\f.vblog.EmptyB\x12Z\x10vblog-core/protob\x06proto3"

var (
	file_proto_analytics_proto_rawDescOnce sync.Once
	file_proto_analytics_proto_rawDescData []byte
)

func file_proto_analytics_proto_rawDescGZIP() []byte {
	file_proto_analytics_proto_rawDescOnce.Do(func() {
		file_proto_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)))
	})
	return file_proto_analytics_proto_rawDescData
}

var file_proto_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_analytics_proto_goTypes = []any{
	(*GetTrendsRequest)(nil),  // 0: vblog.GetTrendsRequest
	(*TrendPoint)(nil),        // 1: vblog.TrendPoint
	(*GetTrendsResponse)(nil), // 2: vblog.GetTrendsResponse
	(*LatestStats)(nil),       // 3: vblog.LatestStats
	(*WatchRequest)(nil),      // 4: vblog.WatchRequest
	(*ChangeEvent)(nil),       // 5: vblog.ChangeEvent
	(*Empty)(nil),             // 6: vblog.Empty
}
var file_proto_analytics_proto_depIdxs = []int32{
	1, // 0: vblog.GetTrendsResponse.points:type_name -> vblog.TrendPoint
	0, // 1: vblog.BlogAnalytics.GetTrends:input_type -> vblog.GetTrendsRequest
	6, // 2: vblog.BlogAnalytics.GetLatestStats:input_type -> vblog.Empty
	4, // 3: vblog.BlogAnalytics.WatchChanges:input_type -> vblog.WatchRequest
	6, // 4: vblog.BlogAnalytics.Ping:input_type -> vblog.Empty
	2, // 5: vblog.BlogAnalytics.GetTrends:output_type -> vblog.GetTrendsResponse
	3, // 6: vblog.BlogAnalytics.GetLatestStats:output_type -> vblog.LatestStats
	5, // 7: vblog.BlogAnalytics.WatchChanges:output_type -> vblog.ChangeEvent
	6, // 8: vblog.BlogAnalytics.Ping:output_type -> vblog.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_analytics_proto_init() }
func file_proto_analytics_proto_init() {
	if File_proto_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_analytics_proto_rawDesc), len(file_proto_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_analytics_proto_goTypes,
		DependencyIndexes: file_proto_analytics_proto_depIdxs,
		MessageInfos:      file_proto_analytics_proto_msgTypes,
	}.Build()
	File_proto_analytics_proto = out.File
	file_proto_analytics_proto_goTypes = nil
	file_proto_analytics_proto_depIdxs = nil
}
